#reglage serveur
server :
  port: 10000

#nom appli
spring :
  application :
    name : ploufMembre
  #acces BD
  datasource :
    url: jdbc:mysql://localhost:3308/plouf_utilisateur?serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #ne pas laisser en prod#
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30000/eureka/